services:
  kvm:
    build: .
    environment:
      #- USER="vmadm"
      - SSH_AUTHORIZED_KEYS=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1gAKtaaJntN7pR+9/OdFAEZq3OWNHSn4jRLWyrsVsHQgsQc5pSGSvG7L5Wu6nW5ZQuTjRCNOXfeyCnxfECN0MnKVCF+RtY0mpkKDZ7pDCjgt1Ev+4NarMWRxMzQFQqVxtmWcZrSVN2UIP70y8396b75UmWS7IHMJ6h4/maQgfggRq9O6plAtgaDgnrlfvRCNV/DqnDmG6KUQHHlVCCoBs6RMhh3Fge3yCamYz8C2vT57Cs7Rs6VxU8G9wpEg4BaorKpe/blPcacvQqjNC0QqtvijyRiqUboKv8aqLxGDufDZyMhC+eL3PI7bpz3yOI5BNVYLkZbuQ+SXUSE5DUbkj PIV AUTH pubkey pkcs11:id=%01;object=%01;token=elijah%40columbiarail.com;manufacturer=piv_II;serial=df75330d61af67d5%0D%04?module-path=/usr/lib64/opensc-pkcs11.so
    volumes:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
      - /dev/hugepages/:/dev/hugepages
      - /dev/vhost-net:/dev/vhost-net
      - ssh_keys:/etc/ssh
      - vm_data:/var/lib/libvirt
      - libvirt_files_secrets:/etc/libvirt/secrets
      - libvirt_files_qemu:/etc/libvirt/secrets
      - libvirt_files_nwfilter:/etc/libvirt/nwfilter
      - libvirt_files_storage:/etc/libvirt/storage

    ports:
      - 8022:8022
    cap_add:
      - net_admin
    group_add:
      - kvm
    networks:
     - vmbr0
    pid: host
    #security_opt:
     # - seccomp=unconfined

networks:
  vmbr0:
    name: vmbr0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.name: "vmbr0" 
      com.docker.network.container_iface_prefix: "vmbr0"
volumes:
  ssh_keys:
  vm_data:
  libvirt_files_secrets:
  libvirt_files_qemu:
  libvirt_files_nwfilter:
  libvirt_files_storage:

